services:
  senpaisearch_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  senpaisearch_app:
    image: senpaisearch_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - senpaisearch_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@senpaisearch_database:5432/app_db

volumes:
  pgdata:        