"""create characters table

Revision ID: 0e6b039fec49
Revises: 5e0657801e32
Create Date: 2024-10-23 15:03:00.830329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6b039fec49'
down_revision: Union[str, None] = '5e0657801e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('anime', sa.String(), nullable=False),
    sa.Column('hierarchy', sa.String(), nullable=False),
    sa.Column('abilities', sa.String(), nullable=False),
    sa.Column('notable_moments', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
